config/routes.rb
Rails.application.routes.draw do
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  resources :histories
  get 'list_items/create'
  get 'list_items/destroy'
  get 'lcart', to: 'lcart#show'
  resources :claims
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  delete '/order_items/deleteAll', to:'order_items#destroy_all'
  get 'cart', to: 'cart#show'
  get 'ofertas', to: 'ofertas#show'
  resources :brands
  resources :categories
  resources :products
  resources :order_items
  resources :list_items
  devise_for :accounts
  resources :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :account
end

app/models/history.rb
class History < ApplicationRecord
    has_one :order_item, class_name: "buyedItems", foreign_key: "buyed_items_id"
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :product
  belongs_to :list
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items,:dependent => :destroy
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end
  

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # If there is a record
    if persisted?
      if product.onsale == true
        product.priceOnsale
      else
        self[:unit_price]
      end
      else
        product.price
      end
    end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    belongs_to :brand
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/lcart_helper.rb
module LcartHelper
end

app/helpers/ofertas_helper.rb
module OfertasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/_footer.html.erb
<footer class="pt-4 bg-dark text-white myFooter pb-0 pt-2 mt-5">
  <div class="offset-md-1 col-md-10 col-xs-12">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <h4 class="mb-3">Contáctanos:</h4>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-white" style="width: 80px;">
          <div class="d-flex flex-row">
            <div class="flex-row">
              <p><i class="fas fa-map-marker mr-2"></i>
                C/Juan Perez Nº8 Las Palmas
              </p>
              <p><i class="far fa-clock mr-2"></i>
                08:00 - 16:00
              </p>
            </div>
            <div class="flex-row ml-4">
              <p><i class="fas fa-phone-alt mr-2"></i>
                +34 928765432 - 665437980
              </p>
              <p><i class="fas fa-envelope mr-2"></i>
                infotronics@gmail.com
              </p>
            </div>
          </div>
        </div>
        <div class="offset-md-2 col-md-4 col-xs-12">
          <h4 class="mb-3">Más sobre Infotronics:</h4>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-white" style="width: 100px;">
          <br>
          <span><i class="fab fa-instagram mr-2 h3 mx-2"></i>
                    </span>
          <span><i class="fab fa-youtube h3 mx-2"></i>
                    </span>
          <span><i class="fab fa-facebook h3 mx-2"></i>
                    </span>
          <span><i class="fab fa-twitter h3 mx-2"></i>
                    </span>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-secondary">
    <div class="mx-auto" style="width:250px">
      <span >Copyright <i class="far fa-copyright"></i> 2021 Infotronics</span>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<header>
<link id="pagestyle" rel="stylesheet" href="light.css">
  <nav class="navbar navbar-expand bg-dark navbar-dark mb-4">
    <div class="container-fluid">
      <%= image_tag "logo_500x500_white.png", class:"d-inline-block align-top", height:'50' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto mb-2 mb-md-0">
          <li class="nav-item">
            <%= link_to "Catálogo", root_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Ofertas", ofertas_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
          <% if cookies[:moon] %>
              <%= link_to 'Dark Mode', sun_path, method: :get , class:"nav-link"%>
              <% else %>
              <%= link_to 'Light Mode', moon_path, method: :get , class:"nav-link"%>
              <% end %>
          </li>
            <% if account_signed_in? %>
            <li class="nav-item">
              <%= link_to "Favoritos", lcart_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to "Carrito", cart_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to "Historial de compra", histories_path, class:"nav-link"  %>
            </li>
          <% end %>

           
<!--          <li class="nav-item">-->
            <%#= link_to "Productos", products_path, class:"nav-link"  %>
<!--          </li>-->
<!--          <li class="nav-item">-->
            <%#= link_to "Marcas",brands_path, class:"nav-link"  %>
<!--          </li>-->
<!--          <li class="nav-item">-->
            <%#= link_to "Categorías", categories_path, class:"nav-link"  %>
<!--          </li> -->

        </ul>

        <form class="form-inline">
           <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" name="search" <%= @search%>>
           <button class="btn btn-outline-success" type="submit">Buscar</button>

           <select class="ml-2" name="selectcategoria" id="selectcategoria" <%= @selectcategoria%>>
             <option value="0">Categoría</option>
             <option value="1">Ordenadores</option>
             <option value="2">Monitores</option>
             <option value="3">Teclados</option>
             <option value="4">Ratones</option>
             <option value="5">Portátiles</option>
           </select>

           <select class="ml-2" name="selectMarca" id="selectMarca" <%= @selectmarca%>>
              <option value="0">Marcas</option>
              <option value="1">Apple</option>
              <option value="2">Microsoft</option>
              <option value="3">Samsung</option>
              <option value="4">LG</option>
              <option value="5">Razer</option>
           </select>

        </form>

        <ul class="navbar-nav mb-2 mb-md-0">
          <%if !account_signed_in? %>
            <li class="nav-item">
              <%= link_to "Crear cuenta", new_account_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Iniciar sesión", new_account_session_path, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Editar perfil", edit_account_registration_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to "Cerrar sesión", destroy_account_session_path, method: :delete, class:"nav-link"  %>
            </li>
             <li class="nav-item">
            <%= link_to 'Eliminar cuenta',accounts_url, method: :delete,data: { confirm: 'Estás seguro?' }, class:"nav-link"  %>
            </li>
          <%end%>
        </ul>

      </div>
    </div>
  </nav>
</header>

<%# <script>

const checkbox = document.getElementById('checkbox');

checkbox.addEventListener('change',() => {

    document.body.classList.toggle('dark')

});
</script> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Infotronics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'logo_32x32.png' %>

    <% if cookies[:moon] %>
    <%= stylesheet_link_tag 'application_dark', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% else %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    
    
  
  </head>

  <body id="bodyjeje" >
    <%= render 'layouts/nav'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>