config/routes.rb
Rails.application.routes.draw do
  get '/moon', to: 'application#moon', as: 'moon'
  get '/sun', to: 'application#sun', as: 'sun'
  resources :histories
  get 'list_items/create'
  get 'list_items/destroy'
  get 'lcart', to: 'lcart#show'
  resources :claims
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  delete '/order_items/deleteAll', to:'order_items#destroy_all'
  get 'cart', to: 'cart#show'
  get 'ofertas', to: 'ofertas#show'
  resources :brands
  resources :categories
  resources :products
  resources :order_items
  resources :list_items
  devise_for :accounts
  resources :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :claims
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/claim.rb
class Claim < ApplicationRecord
  belongs_to :account
end

app/models/history.rb
class History < ApplicationRecord
    has_one :order_item, class_name: "buyedItems", foreign_key: "buyed_items_id"
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :product
  belongs_to :list
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items,:dependent => :destroy
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end
  

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    # If there is a record
    if persisted?
      if product.onsale == true
        product.priceOnsale
      else
        self[:unit_price]
      end
      else
        product.price
      end
    end

  def total
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category
    belongs_to :brand
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    skip_before_action :verify_authenticity_token
	before_action :set_recipe,
only: [:show, :update, :destroy]
# GET /todos
def index
@recipes = Account.all
end
# GET /todos/:id
def show
@recipe = Account.find(params[:id])
#json_response(@recipes)
end
def new
    @recipe = Account.new
end
# POST /todos
def create

    @recipe = Account.new(recipe_params)
    if @recipe.save
    redirect_to @recipe
    else
        render 'new'
    end
    end
    
def edit
        @recipe = Account.find(params[:id])
end	   

# PUT /todos/:id
def update 
    @recipe = Account.find(params[:id])
    
    if @recipe.update(recipe_params)
        redirect_to @recipe
    else
        render 'edit'
    end
end



# DELETE /todos/:id
def destroy 
@recipes.destroy!
head :no_content
end

private
def recipe_params
params.permit(:nombre,:apellidos,:telefono,:cpostal,:direccion,:dni,:pais,:email, :encrypted_password)
end
def set_recipe
@recipes = Account.find(params[:id])
end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/lcart_helper.rb
module LcartHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/ofertas_helper.rb
module OfertasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/edit.html.erb
<h1>Edit Article</h1>
<%= form_with(model: @recipe, local: true) do |form| %>
<% if @recipe.errors.any? %>
<div id="error_explanation">
<h2>
<%= pluralize(@recipe.errors.count, "error") %>
prohibited this article from being saved:
</h2>
<ul>
<% @recipe.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<p><%= form.label :nombre %><br>
<%= form.text_field :nombre %></p>
<p><%= form.label :apellidos %><br>
<%= form.text_field :apellidos %></p>
<p><%= form.label :telefono %><br>
<%= form.number_field :telefono %></p>
<p><%= form.label :email %><br>
<%= form.text_field :email %></p>
<p><%= form.label :cpostal %><br>
<%= form.number_field :cpostal %></p>
<p><%= form.label :direccion %><br>
<%= form.text_field :direccion %></p>
<p><%= form.label :dni %><br>
<%= form.number_field :dni %></p>
<p><%= form.label :pais %><br>
<%= form.text_field :pais %></p>
<p><%= form.submit %> </p>
<% end %>
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing Users</h1>
<table>
<% @recipes.each do |account| %>
<tr>
<td><%= account.nombre %></td>
<td><%= link_to 'Destroy',account_path(account), method: :delete,data: { confirm: 'Are you sure?' } %></td>
<td><%= link_to 'Edit',edit_account_path(account.id) %></td>
<td><%= link_to 'Show',account_path(account) %></td>
</tr>
<% end %>
</table>
<%= link_to "Crear ", new_account_path %>

app/views/accounts/new.html.erb
<%= form_with scope: :account,
url:accounts_path,local: true do |form| %>
<% if @recipe.errors.any? %>
<div id="error_explanation">
<h2>
<%= pluralize(@recipe.errors.count, "error") %>
prohibited this article from being saved:
</h2>
<ul>
<% @recipe.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<p><%= form.label :nombre %><br>
<%= form.text_field :nombre %></p>
<p><%= form.label :apellidos %><br>
<%= form.text_field :apellidos %></p>
<p><%= form.label :telefono %><br>
<%= form.number_field :telefono %></p>
<p><%= form.label :cpostal %><br>
<%= form.number_field :cpostal %></p>
<p><%= form.label :direccion %><br>
<%= form.text_field :direccion %></p>
<p><%= form.label :email %><br>
<%= form.text_field :email %></p>
<p><%= form.label :dni %><br>
<%= form.number_field :dni %></p>
<p><%= form.label :pais %><br>
<%= form.text_field :pais %></p>
<p><%= form.label :contraseña %><br>
<%= form.text_field :encrypted_password %></p>
<p><%= form.submit %> </p>
<% end %>
<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p><strong>Nombre:</strong>
<%= @recipe.nombre %>
</p>
<p><strong>Apellidos:</strong>
<%= @recipe.apellidos %>
</p>
<p><strong>Telefono:</strong>
<%= @recipe.telefono %>
</p>
<p><strong>Codigo Postal:</strong>
<%= @recipe.cpostal %>
</p>
<p><strong>Direccion:</strong>
<%= @recipe.direccion %>
</p>
<p><strong>Dni:</strong>
<%= @recipe.dni %>
</p>
<p><strong>Pais:</strong>
<%= @recipe.pais %>
</p>
<p><strong>Email:</strong>
<%= @recipe.email %>
</p>
<%= link_to 'Edit', edit_account_path(@recipe.id) %>
<%= link_to 'Back', accounts_path %>